export { default as AddLocation } from './AddLocation.vue'
export { default as Forecast } from './Forecast.vue'
export { default as HomePage } from './HomePage.vue'
export { default as MenuPage } from './MenuPage.vue'
export { default as WeatherPage } from './WeatherPage.vue'
export { default as WeatherIcon } from './WeatherIcon.vue'
